server:
  port: 8761
spring:
  application:
    name: fw-register-eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka