server:
  port: 8699
spring:
  application:
    name: fw-gateways-gateway
  profiles:
    active: rewriteresponseheader_route
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: lb://fw-cloud-ribbon-server
          predicates: 
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
  profiles: after_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Before=2091-01-08T18:30:11.965+08:00[Asia/Shanghai]
  profiles: before_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: between_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Between=2020-01-08T18:30:11.965+08:00[Asia/Shanghai],2091-01-08T18:30:11.965+08:00[Asia/Shanghai]
  profiles: between_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Cookie=fwcloud, hello
  profiles: cookie_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Host=**.fwcloud.top
  profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Method=GET,POST
  profiles: method_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Path=/user/{segment},/blue/{segment}
  profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Query=green
  profiles: query_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: remoteaddr_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - RemoteAddr=192.168.1.1/24
  profiles: remoteaddr_route


---
spring:
  cloud:
    gateway:
      routes:
        - id: weight_high
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Weight=group1, 8
        - id: weight_low
          uri: lb://fw-cloud-ribbon-server-bak #修改配置，换一个服务名启动
          predicates:
              - Weight=group1, 2
  profiles: weight_route



---
spring:
  cloud:
    gateway:
      routes:
        - id: prefixpath_route
          uri: lb://fw-cloud-ribbon-server
          predicates: 
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters: #前缀
            - PrefixPath= /user
  profiles: prefixpath_route



---
spring:
  cloud:
    gateway:
      routes:
        - id: rewritepath_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
            - RewritePath=/gateway/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: setpath_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Path=/{segment}
          filters:
            - SetPath=/user/{segment}
  profiles: setpath_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: strippath_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
  profiles: strippath_route

---
spring:
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: strippath_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - Path=/gateway/**
  profiles: default_path_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
            - AddRequestHeader=X-Request-id, fwcloud
  profiles: add_request_header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: add_request_parameter_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
            - AddRequestParameter=sys, fwcloud
  profiles: add_request_parameter_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: add_response_header_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
            - AddResponseHeader=sys, fwcloud
  profiles: add_response_header_route



---
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: preserve_host_route  #PreserveHostHeader GatewayFilter Factory没有参数。 此过滤器设置路由过滤器将检查的请求属性，以确定是否应发送原始主机头，而不是http客户端确定的主机头
#          uri: lb://fw-cloud-ribbon-server
#          predicates:
#          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
#          filters:
#          - PreserveHostHeader
#  profiles: preserve_host_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: dedupe_response_header_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin,RETAIN_FIRST
  profiles: dedupe_response_header_route
#  当下游和 Spring Cloud Gateway 都设置跨域时，将在 Response Header 中移除重复的 Access-Control-Allow-Credentials 和 Access-Control-Allow-Origin。
#
#  strategy 可设置的值以及配置方式如下：
#
#  RETAIN_FIRST：保留第一个值【默认】
#  RETAIN_LAST：保留最后一个值
#  RETAIN_UNIQUE：保留所有唯一值，以它们第一次出现的顺序保留

---
spring:
  cloud:
    gateway:
      routes:
        - id: map_request_header_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
          - MapRequestHeader=Blue, X-Request-Red
  profiles: map_request_header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: redirect_to_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
          - RedirectTo=302, http://www.163.com
  profiles: redirect_to_route


---
spring:
  cloud:
    gateway:
      routes:
        - id: remove_request_header_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
          - RemoveRequestHeader=Blue
  profiles: remove_request_header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: remove_response_header_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
          - RemoveResponseHeader=Content-Type
  profiles: remove_response_header_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: remove_response_parameter_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
          - RemoveRequestParameter=ids
  profiles: remove_response_parameter_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: rewritelocationresponseheader_route
          uri: lb://fw-cloud-ribbon-server
          predicates:
          - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
          - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
  profiles: rewritelocationresponseheader_route

